// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import health "github.com/atsu/goat/health"

import mock "github.com/stretchr/testify/mock"

// ChatOpsClient is an autogenerated mock type for the ChatOpsClient type
type ChatOpsClient struct {
	mock.Mock
}

// Health provides a mock function with given fields:
func (_m *ChatOpsClient) Health() (health.Event, error) {
	ret := _m.Called()

	var r0 health.Event
	if rf, ok := ret.Get(0).(func() health.Event); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(health.Event)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SlackAtsuEvent provides a mock function with given fields: templateName, fields
func (_m *ChatOpsClient) SlackAtsuEvent(templateName string, fields map[string]string) error {
	ret := _m.Called(templateName, fields)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, map[string]string) error); ok {
		r0 = rf(templateName, fields)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
